# -*- coding: utf-8 -*-
"""DataCleaning.ipnyb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ch3Jxm-xs-LodZadBXbgWhv2Gj2FseQM

#Apartments Prices Data Cleaning

##Import libs and data
"""

import pandas as pd
import numpy as np
from datetime import date
from google.colab import drive
drive.mount('/content/gdrive')

olx_url = 'https://raw.githubusercontent.com/sztyberj/ApartmentsPricesInPoland/main/Data%20Collection/raw_olx.csv'
oto_url = 'https://raw.githubusercontent.com/sztyberj/ApartmentsPricesInPoland/main/Data%20Collection/raw_oto.csv'

raw_olx = pd.read_csv(olx_url, sep=';', header=None)
raw_oto = pd.read_csv(oto_url, sep=';', header=None)

raw_olx.head(5)

raw_oto.head(5)

"""##Cleaning raw OtoDom data"""

#Delete irrelevant columns
del raw_oto[4]
del raw_oto[6]
del raw_oto[8]
del raw_oto[9]
del raw_oto[10]
del raw_oto[11]
del raw_oto[12]

raw_oto

#Rename columns
raw_oto.columns = ['City', 'Price', 'Price/sqr_meter', 'Area', 'Rooms', 'Level']

raw_oto.City.unique()

"""### Price column

**Delete polish words, symbols and spaces**
"""

raw_oto.Price = raw_oto.Price.str.replace(' zł', '')
raw_oto.Price = raw_oto.Price.str.replace(' ', '')
raw_oto.Price

"""**Convert into numeric type**"""

#Change ',' into '.'
raw_oto.Price = raw_oto.Price.str.replace(',', '.')

raw_oto.Price = pd.to_numeric(raw_oto.Price)

raw_oto

"""###Price/sqr_meter column

**Delete symbols and spaces**
"""

raw_oto['Price/sqr_meter'] = raw_oto['Price/sqr_meter'].str.replace(' zł/m²', '')
raw_oto['Price/sqr_meter'] = raw_oto['Price/sqr_meter'].str.replace('zł/м²', '')
raw_oto['Price/sqr_meter'] = raw_oto['Price/sqr_meter'].str.replace(' ', '')
raw_oto['Price/sqr_meter']

"""**Convert into numeric type**"""

raw_oto['Price/sqr_meter'] = raw_oto['Price/sqr_meter'].str.replace(',', '.')

raw_oto['Price/sqr_meter'] = pd.to_numeric(raw_oto['Price/sqr_meter'])

raw_oto

"""###Area column

**Delete polish words from rows and symbols**
"""

#Area column
raw_oto['Area'] = raw_oto['Area'].str.replace('Powierzchnia', '')
raw_oto['Area'] = raw_oto['Area'].str.replace(' m²', '')

"""**Convert into numeric type**"""

raw_oto['Area'] = raw_oto['Area'].str.replace(',', '.')

raw_oto['Area'] = pd.to_numeric(raw_oto['Area'])

"""###Rooms column

**Delete polish words from rows and spaces**
"""

raw_oto['Rooms'] = raw_oto['Rooms'].str.replace('Liczba pokoi', '')
raw_oto['Rooms'] = raw_oto['Rooms'].str.replace(' ', '')
raw_oto.Rooms.unique()

raw_oto['Rooms'] = raw_oto['Rooms'].str.replace('więcejniż10', '10')
raw_oto.Rooms.unique()

"""**Convert into numeric type**"""

raw_oto['Rooms'] = pd.to_numeric(raw_oto['Rooms'])

"""###Level column

**Delete polish words and spaces**
"""

raw_oto['Level'] = raw_oto['Level'].str.replace('Piętro', '')
raw_oto.Level.unique()

raw_oto['Level'] = raw_oto['Level'].str.replace('parter', '0')
raw_oto['Level'] = raw_oto['Level'].str.replace('suterena', '-0.5')
raw_oto['Level'] = raw_oto['Level'].str.replace('zapytaj', 'nan')
raw_oto['Level'] = raw_oto['Level'].str.replace('poddasze', '0.5')
raw_oto['Level'] = raw_oto['Level'].str.replace('> ', '')
raw_oto.Level.unique()

"""**Drop NaN values**"""

raw_oto['Level'].replace('nan', np.nan, inplace=True)

raw_oto.dropna(inplace=True)
raw_oto.Level.unique()

raw_oto.Level = raw_oto.Level.astype('str')

"""**Temporary data frame**"""

tmp = raw_oto.Level.str.split('/', n=1, expand=True)
tmp[0].unique()

"""**Append new column**"""

raw_oto['New_Level'] = tmp[0]

raw_oto.head(10)

"""**Delete old Level column**"""

del raw_oto['Level']
raw_oto.columns = raw_oto.columns.str.replace('New_Level', 'Level')
raw_oto

"""**Convert into numeric type**"""

raw_oto['Level'] = pd.to_numeric(raw_oto['Level'])

"""###Info about DataFrame"""

raw_oto.info()

raw_oto.describe()

pd.set_option('display.float_format', lambda x: '%.2f' % x)

raw_oto.describe()

"""##Cleaning raw Olx data"""

raw_olx

del raw_olx[2]
del raw_olx[5]
del raw_olx[6]
del raw_olx[7]

raw_olx

raw_olx.columns = ['City', 'Price', 'Price/sqr_meter', 'Level', 'Area', 'Rooms']

raw_olx.City.unique()

"""###Price column

**Delete symbols and spaces**
"""

raw_olx.Price = raw_olx.Price.str.replace(' zł', '')
raw_olx.Price = raw_olx.Price.str.replace(' ', '')
raw_olx.Price = raw_olx.Price.str.replace(',', '')

raw_olx.Price

"""**Convert into numeric type**"""

raw_olx.Price = pd.to_numeric(raw_olx.Price)

"""###Price/sqr_meter

**Delete symbols and spaces**
"""

raw_olx['Price/sqr_meter'] = raw_olx['Price/sqr_meter'].str.replace('Cena za m²: ', '')
raw_olx['Price/sqr_meter'] = raw_olx['Price/sqr_meter'].str.replace(' zł/m²', '')
raw_olx['Price/sqr_meter'] = raw_olx['Price/sqr_meter'].str.replace(',', '.')

raw_olx['Price/sqr_meter']

"""**Convert into numeric type**"""

raw_olx['Price/sqr_meter'] = pd.to_numeric(raw_olx['Price/sqr_meter'])

"""###Level column

**Delete polish words and spaces**
"""

raw_olx.Level = raw_olx.Level.str.replace('Poziom: ', '')

raw_olx.Level.unique()

raw_olx.Level = raw_olx.Level.str.replace('Umeblowane: Nie', 'nan')
raw_olx.Level = raw_olx.Level.str.replace('Umeblowane: Tak', 'nan')
raw_olx.Level = raw_olx.Level.str.replace('Powyżej 10', '11')
raw_olx.Level = raw_olx.Level.str.replace('Poddasze', '0.5')
raw_olx.Level = raw_olx.Level.str.replace('Suterena', '-0.5')
raw_olx.Level = raw_olx.Level.str.replace('Parter', '0')

raw_olx.Level.unique()

"""**Drop NaN values**"""

raw_olx.Level.replace('nan', np.nan, inplace=True)
raw_olx.dropna(inplace=True)
raw_olx.Level.unique()

"""**Convert into numeric type**"""

raw_olx.Level = pd.to_numeric(raw_olx.Level)

"""###Area column

**Delete polish words and symbols**
"""

raw_olx.Area = raw_olx.Area.str.replace('Powierzchnia: ', '')
raw_olx.Area = raw_olx.Area.str.replace(' m²', '')
raw_olx.Area = raw_olx.Area.str.replace(',', '.')
raw_olx.Area = raw_olx.Area.str.replace(' ', '')
raw_olx.Area.unique()

"""**Convert into numeric type**"""

raw_olx.Area = pd.to_numeric(raw_olx.Area)

"""###Rooms column

**Clear polish words and symbols**
"""

raw_olx.Rooms

raw_olx.Rooms = raw_olx.Rooms.str.replace('Liczba pokoi: ', '')
raw_olx.Rooms = raw_olx.Rooms.str.replace(' pokoje', '')
raw_olx.Rooms.unique()

raw_olx.Rooms = raw_olx.Rooms.str.replace(' pokój', '')
raw_olx.Rooms = raw_olx.Rooms.str.replace(' i więcej', '')
raw_olx.Rooms.unique()

"""**Convert into numeric type**"""

raw_olx.Rooms = pd.to_numeric(raw_olx.Rooms)

"""###Reorganization of columns"""

raw_olx = raw_olx.reindex(columns=['City', 'Price', 'Price/sqr_meter', 'Area', 'Rooms', 'Level'])

"""###Info about DataFrame"""

raw_olx.info()

raw_olx.describe()

"""Too high difference between 75% and max value in Area column.
Too high difference between 75% and max value in Price column.

**Delete too high values**
"""

raw_olx = raw_olx[raw_olx.Area != 865000.00]

raw_olx = raw_olx[raw_olx.Price != 69085710.00]

raw_olx.describe()

"""##Merge DataFrames and delete duplicates"""

data = pd.concat([raw_olx, raw_oto], ignore_index=True)
data

data.drop_duplicates(inplace=True)

data.info()

data.describe()

"""**Sort DataFrame by City column**"""

data.sort_values(by=['City'], inplace=True)

"""**Rename columns**"""

data.columns = ['City', 'Price [PLN]', 'Price/sqr_meter [PLN]', 'Area [m^2]', 'Rooms', 'Level']

data.reset_index(drop=True, inplace=True)

data

"""##Save Data Frame into Google Drive"""

today = date.today()
d = today.strftime("%m%d%y")

xlsx = data.to_excel(f'/content/gdrive/My Drive/apartments_prices_in_poland_{d}.xlsx')
csv = data.to_csv(f'/content/gdrive/My Drive/apartments_prices_in_poland_{d}.csv', sep=';')

"""#Data description

The values -0.5 and 0.5 in Level column mean:

-0.5 - basement

0.5 - attic
"""